first commit
kertnik05/LVA pull request #4
Opened 2020-10-28 12:29 UTC by MarcuzAizen

Hahaha, usbon sa nakog balik, ,wa jud nagkadimao

2020-10-28 12:49 UTC, kertnik05 commented on .env.example
> +DB_PASSWORD=root
you are not supposed to configure the db here in this file. Do that in .env file

2020-10-28 12:52 UTC, MarcuzAizen commented on .env.example
> +DB_PASSWORD=root
Ahh okay

2020-10-28 12:55 UTC, kertnik05 commented
Also change the PR title into something relevant to what you did

2020-10-28 12:56 UTC, kertnik05 commented
Also check this out:
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/working-with-forks

2020-10-28 13:07 UTC, kertnik05 requested changes
In AcadYearController,, remove all comments, create() & edit() function

2020-10-28 13:08 UTC, kertnik05 commented
> In AcadYearController,, remove all comments, create() & edit() function

also, the AcadYearController should be in the Controllers/API directory

2020-10-31 14:00 UTC, kertnik05 requested changes

2020-10-31 14:00 UTC, kertnik05 commented on app/Http/Controllers/AcadYearController.php
> +namespace App\Http\Controllers;
API controllers should be in Controllers/API directory

2020-11-02 03:50 UTC, kertnik05 requested changes

2020-11-02 03:50 UTC, kertnik05 commented on app/Http/Controllers/AcadYearController.php
> +    }
remove create() function

2020-11-02 03:50 UTC, kertnik05 commented on app/Models/AcadYear.php
> +    //protected $table = "acad_years";
remove comment

2020-11-02 03:50 UTC, kertnik05 commented on routes/api.php
> +Route::apiResource("acad-year", AcadYearController::class);
url should be in plural form. change url to plural form (acad-year -> acad-years)

2020-11-02 03:50 UTC, kertnik05 commented on routes/api.php
> +//Route::put("acad-year", [AcadYearController::class, "update"]);
remove comment

2020-11-02 07:00 UTC, kertnik05 requested changes

2020-11-02 07:00 UTC, kertnik05 commented on database/migrations/2020_10_28_065725_create_acad_years_table.php
> +            $table->date('end')->unique();
change data type to `year`

2020-11-03 05:38 UTC, closed without merging