Create attendance crud UI
kertnik05/LVA pull request #57
Opened 2020-12-22 23:31 UTC by MarcuzAizen

please review, thanks

![1](https://user-images.githubusercontent.com/38231438/102942527-935b3500-44f0-11eb-9f9c-62d7685cbe64.png)
![2](https://user-images.githubusercontent.com/38231438/102942538-97875280-44f0-11eb-8f5f-04dc717f9ed5.png)
![3](https://user-images.githubusercontent.com/38231438/102942535-96562580-44f0-11eb-80d7-11493aa1e21f.png)
![4](https://user-images.githubusercontent.com/38231438/102942532-95bd8f00-44f0-11eb-8f05-20a5606e9793.png)
![5](https://user-images.githubusercontent.com/38231438/102942525-92c29e80-44f0-11eb-81aa-7e66c246db81.png)
![6](https://user-images.githubusercontent.com/38231438/102942536-96eebc00-44f0-11eb-98ab-01f69ff827c1.png)
![7](https://user-images.githubusercontent.com/38231438/102942531-9524f880-44f0-11eb-81bb-51d76e8d9df5.png)
![8](https://user-images.githubusercontent.com/38231438/102942530-948c6200-44f0-11eb-92e0-dbe00dbb78b2.png)
![9](https://user-images.githubusercontent.com/38231438/102942529-93f3cb80-44f0-11eb-96c9-4cd2c56e3613.png)
![10](https://user-images.githubusercontent.com/38231438/102942522-90f8db00-44f0-11eb-997c-572540519e82.png)

2020-12-23 04:09 UTC, kertnik05 commented
@MarcuzAizen  redesign the ui for the attendance crud. I think it should include the section, grade_level, track, student & subject sched. Imagine what would be records in a class record of the teacher.

2020-12-23 04:44 UTC, kertnik05 requested changes
@MarcuzAizen  redesign the ui for the attendance crud. I think it should include the section, grade_level, track, student & subject sched. Imagine what would be records in a class record of the teacher.

2021-01-15 01:06 UTC, MarcuzAizen commented
![Screenshot from 2021-01-15 08-57-36](https://user-images.githubusercontent.com/38231438/104667355-e18adf00-5710-11eb-86c5-201384706536.png)
![Screenshot from 2021-01-15 08-58-02](https://user-images.githubusercontent.com/38231438/104667366-e3ed3900-5710-11eb-80b6-afa77a89ef59.png)
![Screenshot from 2021-01-15 08-57-46](https://user-images.githubusercontent.com/38231438/104667368-e485cf80-5710-11eb-936c-aadf1b66248a.png)

2021-01-17 02:30 UTC, kertnik05 requested changes

2021-01-17 02:30 UTC, kertnik05 commented on app/Http/Controllers/API/AttendanceController.php
> +    }
For what purpose is this function?

2021-01-17 02:30 UTC, kertnik05 commented on app/Http/Controllers/API/AttendanceController.php
> +            'schedule.section'
`Call to undefined relationship [schedule] on model [App\Models\User]`. Relationship from user to schedule model is not `schedule` but `schedules`. Change to `schedules`

2021-01-17 02:30 UTC, kertnik05 commented on resources/js/components/teacher/AttendanceModal.vue
> +        },
add new line here to have some space between function for better readability

2021-01-17 02:30 UTC, kertnik05 commented on resources/js/pages/teacher/Attendance.vue
> +    },
if you don't have a search function implemented, you can remove this lines and lodash

2021-01-17 02:30 UTC, kertnik05 commented on resources/js/pages/teacher/Attendance.vue
> +        },
for what purpose is this `sortFunc()`? I don't  see this being implemented in this component.

2021-01-17 02:30 UTC, kertnik05 commented on resources/js/pages/teacher/Attendance.vue
> +        },
add new line here to have some space between function for better readability

2021-01-17 02:38 UTC, kertnik05 commented
Also please write appropriate and good commit message

2021-01-27 03:16 UTC, MarcuzAizen commented
![Screenshot from 2021-01-27 10-47-05](https://user-images.githubusercontent.com/38231438/105937692-08420180-6091-11eb-9cf9-2d9379e7b34d.png)

2021-05-05 07:04 UTC, closed without merging